#!/bin/bash
# This script:
# - Clones the WP Plugin Boilerplate
# - Renames the directory and files
# Ubuntu: add this script to /usr/local/bin
# Make it executable, then you can invoke it by typing "plugin" in the terminal.

# ---------------------------------
boilerplate_repo=git@github.com:DevinVinson/WordPress-Plugin-Boilerplate.git

setup_plugin () {
  git clone "$boilerplate_repo"
  echo "We are at: ""$PWD"
  echo -e "Choose a name for the new plugin:"
  read -r plugin_name

  # Spaces to dashes
  plugin_name=${plugin_name// /-}

  # Get the name in a format to replace plugin_name
  function_name=${plugin_name//-/_}
  function_name=${function_name,,}

  # Dashes to spaces - an array of words
  class_name=(${plugin_name//-/ })

  # Capitalise first letter
  uc_class_name=${class_name[*]^}

  # Spaces to underscores
  snake_class_name=${uc_class_name// /_}
  class_name=$snake_class_name

  echo "Plugin Name is: ""$plugin_name"
  echo "Class Name is: ""$snake_class_name"
  cp -r "$PWD"/WordPress-Plugin-Boilerplate/plugin-name "$PWD"/"$plugin_name"

  # Apply the Rename, verbose output lists changes
  find "$PWD"/"$plugin_name" -iname "*" -exec sed -i 's/plugin_name/'"${function_name}"'/g' '{}' \; -exec sed -i 's/Plugin_Name/'"${class_name}"'/g' '{}' \; -exec sed -i 's/plugin-name/'"${plugin_name}"'/g' '{}' \; -exec rename -v 's/plugin-name/'"${plugin_name}"'/g' '{}' \;

}

setup_node () {
  cd "$PWD"/"$plugin_name" || exit

  # Note: npm runs without sudo if node has been installed on your system by the nvm method:
  # https://github.com/creationix/nvm (recommended!)
  # Otherwise, the npm install command should run as sudo, followed by bower install.
  # For this case comment out line 133 & enable lines 134 & 135)
  # Or move to the theme directory after installation is complete and run sudo npm install followed by bower install
  npm install
  # sudo npm install
  # bower install
  # For sage, overtly call bower
  bower install
}

run_gulp () {
cd "$PWD"/"$plugin_name" || exit
gulp watch
}

setup_repo () {
cd "$PWD"/"$plugin_name" || exit

# remove existing git repo
sudo rm -rf "$PWD"/"$plugin_name"/.git
git init

repo_name=$1

  invalid_credentials=0

  if [ "$repo_name" = "" ]; then
    echo "  Repo name (hit enter to use '$plugin_name')?"
    read -r repo_name
  fi

  if [ "$repo_name" = "" ]; then
    repo_name=$plugin_name
  fi

  username=$(git config github.user)
  if [ "$username" = "" ]; then
    echo "  Could not find username, run 'git config --global github.user <username>'"
    invalid_credentials=1
  fi

  token=$(git config github.token)
  if [ "$token" = "" ]; then
    echo "  Could not find token, run 'git config --global github.token <token>'"
    invalid_credentials=1
  fi

  if [ "$invalid_credentials" -eq "1" ]; then
    return 1
  fi

  echo -n "  Creating Github repository '$repo_name' ..."
  curl -u "$username:$token" https://api.github.com/user/repos -d '{"name":"'$repo_name'"}' > /dev/null 2>&1
  echo " done."

  echo -n "  Pushing local code to remote ..."
  git remote add origin git@github.com:$username/$repo_name.git > /dev/null 2>&1
  git push -u origin master > /dev/null 2>&1
  git add -A
  git commit -m "First Commit"
  git push origin master
  echo " done."

}

  setup_plugin

	read -p "Set up a new GitHub repo for $plugin_name? [y/N]" yn
	case $yn in
	[Yy]* ) setup_repo;;
	[Nn]* ) ;;
	* ) echo "Please answer yes or no.";;
	esac

	#read -p "Do you want to install and activate the Roots \"Soil\" plugin? [y/N]" yn
	#case $yn in
	#[Yy]* ) install_soil;;
	#[Nn]* ) exit ;;
	#* ) echo "Please answer yes or no.";;
	#esac

	#read -p "Do you want to go to the $plugin_name theme and install node dependencies? [y/N]" yn
	#case $yn in
	#[Yy]* ) setup_node;;
	#[Nn]* ) exit ;;
	#* ) echo "Please answer yes or no.";;
	#esac

	#read -p "Do you want to activate the $plugin_name theme? [y/N]" yn
	#case $yn in
	#[Yy]* ) activate_theme;;
	#[Nn]* ) exit ;;
	#* ) echo "Please answer yes or no.";;
	#esac

	#read -p "Move to the theme directory and run the gulp build task? [y/N]" yn
	#case $yn in
	#[Yy]* ) run_gulp;;
	#[Nn]* ) exit ;;
	#* ) echo "Please answer yes or no.";;
	#esac

#sitelocation="Access your new site: http://localhost/"
#sitelocation+=$wp_dir
echo -e "------------------------------------------------"
echo -e "Finished!"
#echo $sitelocation
echo -e "------------------------------------------------"
